language: java
install: true
dist: trusty
jdk: openjdk11
before_script:
  - chmod +x gradlew

script:
  - ./gradlew build --scan -s
#  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
